name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Checkout submodules
      uses: srt32/git-actions@v0.0.3
      with:
        args: git submodule update --init --recursive

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build

      run: |
        mkdir target
        timestamp=$(date -u +%Y%m%d-%H%M%S)
        echo "::set-env name=TIMESTAMP::${timestamp}"
        bash prepareBPCartefacts-github.sh target github ${timestamp}z DELETE-REPOSITORY-FILES-AS-WELL

    - uses: actions/upload-artifact@v2
      with:
        name: bpc-semantics-github-${{ env.TIMESTAMP }}z
        path: ./*
